name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  cd:
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Deploy Latest Code
        run: |
          cd /home/ubuntu/github-ci-cd-project
          git pull origin main
          npm install
          pm2 restart index --update-env
