name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - name: Checkout Latest Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          cd github-ci-ci-project
          npm i

      - name: Run Tests
        run: |
          cd /github-ci-ci-project
          npm run test

  cd:
    needs: ci
    runs-on: self-hosted

    steps:
      - name: Restart App
        run: pm2 restart backend-prod
